name: CI

on: [push]

jobs:
  testing:
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache .yarn/cache
        uses: actions/cache@v1.0.0
        with:
          path: .yarn/cache
          key: yarncache-${{ matrix.node-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarncache-${{ matrix.node-version }}-

      - name: Cache node_modules
        uses: actions/cache@v1.0.0
        with:
          path: node_modules
          key: nodemodules-${{ matrix.node-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: nodemodules-${{ matrix.node-version }}-

      - name: Install deps
        run: yarn install

      - name: Testing @fluer/lys
        run: |
          cd packages/lys
          yarn test --coverage --verbose

  build-lint:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        steps: [build, lint]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Cache .yarn/cache
        uses: actions/cache@v1.0.0
        with:
          path: .yarn/cache
          key: yarncache-${{ matrix.node-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarncache-${{ matrix.node-version }}-

      - name: Cache node_modules
        uses: actions/cache@v1.0.0
        with:
          path: node_modules
          key: nodemodules-${{ matrix.node-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: nodemodules-${{ matrix.node-version }}-

      - name: Install deps
        run: yarn install

      - name: Build package
        if: ${{ matrix.steps == 'build' }}
        run: |
          cd packages/lys
          yarn prepublishOnly

      - name: Linting @fleur/lys
        if: ${{ matrix.steps == 'lint' }}
        run: |
          cd packages/lys
          yarn eslint ./src
